import { Poppins, Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Annoucebar from "@/components/Annoucebar";
import Footer from "@/components/Footer";

const poppins = Poppins({ weight: ["100", "200", "300", "400", "500", "600", "700"], subsets: ["devanagari"] });

export const metadata = {
  title: "Craftoon: A priceless Art",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={poppins.className}>
        <Annoucebar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
